language: node_js
node_js:
- 12
install:
- npm install
script:
- npm run lint-check
- npm run audit-production
- npm test
- npm run build-artifacts
- npm run unzip-artifacts
deploy:
  - provider: releases
    api_key:
      secure: OC6GQ0Axqc4YdEsdSSch884f1BaUO22cg5wvlMaTwJPZX7Ok+RbRUbS97ncGlXAAXOd7Wf5pio3enC9+RhxOQx5IMpq+HDmT/u1QQBRE41uNhOyviGKdHWPG+GvH/Yj+4bLtMIVmnfp+YhWfBLBqPDdyf0hqafCJddoib1lrLgrzzxwhGMTePlwIV0dKOJnoh1P9L1tJBMvXkr6DNEIDm0ncRK2Ne5Di4rYuFvR/6tCeoh1Iril/ROM2XqhbEFDDoc0+DLiBngGPuT3+sTh+2NhWBQXTXsM+PsEZL9F4fBGchZHu7qEntzq//uR+cVRWblDIYXXcpeQN4caD8/tKvE2Z17dkYaRM9tP2wt3avnsoQg+FVkEjeMwEXWbU4Y7NT7rjwkv49u34ugSz/EIWzihyG6o4nl2Diply81xlhbRsuDU/JKhcrJbhyjdoG8eqvmbe2U/Dz4xLxiUsoVUWkBnfArdYbLfxvTHAbFrcdpqfP9XWDvHP35ef5uiJHXHj6JwCsgIvxKnOVm9RBNig3nKHAU0fhuPVGT78u9r60BxmhkAe+Kcaxu7Lxbhgr3b2BG+Q3SW9g0fyVAlsNNTHkSJHS1BZGvE8pGPrtrdp2r9QJWKGHdBYBr7oF+a1CFmIOd9hWnKPTCIMTfETFMU1w1ZVHn6jFEkHaj3yvZDymek=
    file_glob: true
    file: dist/artifacts/*
    on:
      repo: fortinet/fortigate-autoscale-aws
      branch: main
      tags: true
    skip_cleanup: true
  - provider: script
    script: ~/.local/bin/aws s3 sync dist s3://fortinet-github-aws-release-artifacts/fortigate-autoscale-aws/$TRAVIS_BRANCH --region=us-west-2 --delete --acl=public-read
    on:
      repo: fortinet/fortigate-autoscale-aws
      branch: main
    skip_cleanup: true
env:
  global:
  - secure: ILZ0OQjzHd9HeeYQJ54r5b8hS4mgR1GffBhrR9O35mCC/JeCwghslKxiNoTpaVBxGgSlAM/XAagsg5dN04orQ/YYdbYljYuEWUqHkSKF8ZD6rXiDp2ddEFOAPRVSoVGUpPoucY253hcUHEp8nIia4Mcyu+af0I861pIi4gbu1G4wvZ8w1U9hQGyRJeEqd1KcVec4xasJqZAO7kJEYQYlJHXym84z5bEz9dB5oTtijLKjcXMxZwZ4G3jmikVQrRzTQOq8TPUCLac7WSdpU6rTYtY5A8gyCaRJZxyAumwDh5ujdoFQJNggRuf8vdxk8uPXBX4nLBy8Y0BETqXGh+59EltPs08P1muotDcsUuxuMEo5p9lEaFCvs23JmqgZ/qdXFAF8O967SnWMY5Ef//ofpDxi1wEu+4i/scKM6upSOhVkKatuRqay9pRhiaLJwgYMEcPdTUb+gsFmcqgRifunM1lFX/d5ao0g7fMBsrw0HU6/e1NOk/nL+Jbs9GpV08/TBIdFLGsBZ+eaQ52lLoi4wmZt2kZVHGl1lpsIRCttAHuz8U1f2iaT6/j/i9RjoSv05paYGpdi2rhS5Y+dmzeIQx7jeWcLkmIZCgl94Zuf2NRsIpSnfYWOT+qnKjia4xswLbCvu92LEgCUZkFi6iE8FsEiJGrStlnbDlo6ChVOXtY=
  - secure: w7VumRTsRv39qtRLYmsvjWzIaQa4wCsDy1d6Ybc/DlDp8DuTW5wXlMl029Ydpm2BPg2nrJR8eLrQmrluvWvx+S0pII/wOTjSEY5qS5sMoFMvcVgzDA4lSpzSsWqbU3FRx5ZvRECLisvcXGZMU14YN1VfvCMMlRgSDQX2Xoms3dzwUKuAnqKU2j72JFsRrJS/XISin+C2KLUKh6m1nzQpgseg/ujShJtDq/iopqK5Mr5CnEUz3rrzprbiOwE+DjUfd6ATKObWcVSu3dgG1AwQV7J9eVMIFoA6vE1bC4Ud56OxkufzvyR9ntO1w/wqGtwOAeUxcqBQWk7S0pW6Bg8PFAgDS39vk6VPyIhQE4D12DjqnmF6B6ssBY2Sq8qaNrMtVEm1HyWAi/q+7BMwWTz78Ow2vQj5iQsneWksBlYfc/Bn42ORq+DplPu7Fb2NFW7sjonVdYLeNSgOlqqkYEIecLoptlODZIsglJCTA9SGy6HlKA16i9GR/WD9t6Wi4sSMhuMCNX2J62GyUYjzLjovgC77WkBMQhgt4MCRFnHfBRQMEzFEe64P7ZCe19riYfzIJYf2hD9luQiPA6HMa183yHRakN/+hGj1lTJdLBgIUcOvk4hRyRfmtNKjWNx7WrAtRnVE85vXKxydwq5HzAoFbZGAPMZuPDAx1LciqtiinTc=
